# job.yaml
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: fastqc-
  namespace: default
  labels:
    kueue.x-k8s.io/queue-name: user-queue
spec:
  parallelism: 1
  completions: 1
  suspend: true
  template:
    spec:
      containers:
      - name: dummy-job
        image: openflighthpc/genome:latest
        command: [ "/bin/bash", "-c", "python3 /app/script.py && echo '' && ls / && ls /app/ &&cat /app/sample_data_fastqc.html " ]
        env:
          - name: MINIO_IP
            value: <minio ip like "10.151.15.78">
          - name: MINIO_PORT
            value: <minio port like "31100">
          # Minio Access Key   
          - name: MINIO_AKEY
            value: <minio-access-key>
          # Minio Secret Key   
          - name: MINIO_SKEY
            value: <minio-secret-key>
          - name: BUCKET_NAME
            value: <minio bucket name like "genome">
        resources:
          requests:
            cpu: 500m
            memory: "2000Mi"
      restartPolicy: Never
