# job.yaml
---
apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: pytorch-simple
  namespace: default
  labels:
    kueue.x-k8s.io/queue-name: user-queue
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: openflighthpc/pytorch:latest
              imagePullPolicy: Always
              command:
                - "python3"
                - "/opt/mnist/src/main.py"
              resources:
                requests:
                  cpu: 500m
                  memory: "1000Mi"
              env:
                - name: MINIO_IP
                  value: <minio ip like "10.151.15.78">
                - name: MINIO_PORT
                  value: <minio port like "31100">
                # Minio Access Key   
                - name: MINIO_AKEY
                  value: <minio-access-key>
                # Minio Secret Key   
                - name: MINIO_SKEY
                  value: <minio-secret-key>
                - name: BUCKET_NAME
                  value: <minio bucket name like "pytorch">

    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: openflighthpc/pytorch:latest
              imagePullPolicy: Always
              command:
                - "python3"
                - "/opt/mnist/src/main.py"
              resources:
                requests:
                  cpu: 500m
                  memory: "1000Mi"
              env:
                - name: MINIO_IP
                  value: <minio ip like "10.151.15.78">
                - name: MINIO_PORT
                  value: <minio port like "31100">
                # Minio Access Key   
                - name: MINIO_AKEY
                  value: <minio-access-key>
                # Minio Secret Key   
                - name: MINIO_SKEY
                  value: <minio-secret-key>
                - name: BUCKET_NAME
                  value: <minio bucket name like "pytorch">
